- name: Get changed files
  id: changed-files
  uses: tj-actions/changed-files@v42

- name: Purge jsDelivr Cache
  env:
    ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
  run: |
    for file in $ALL_CHANGED_FILES; do
      echo "Requesting cache purge for: $file"
      curl -X POST "https://purge.jsdelivr.net/gh/${{ github.repository }}@master/$file"
    done