name: Update Latest Release Loadstrings

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Release Notes
        run: |
          python .github/scripts/generate_release_notes.py

      - name: Generate Dynamic Release Name
        id: gen_name
        run: |
          # Tạo chuỗi định dạng: Năm.Tháng.Ngày (VD: 2026.05.18)
          REL_NAME=$(python -c "import datetime, random, string; print(datetime.datetime.now().strftime('%Y.%m.%d.'))")
          echo "DYNAMIC_NAME=$REL_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.DYNAMIC_NAME }}"
          name: "${{ env.DYNAMIC_NAME }}"
          bodyFile: "release_notes.md"
          prerelease: false